#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0
bspc config top_padding 15 # for dzen statusbar, maybe set -dock in dzen invocation?

bspc rule -r '*'

if [ -f /sys/class/power_supply/BAT0/capacity ] && command -v acpi; then
    statusbar() {
        echo "$(bspc wm -g) | $(acpi -b) | $(date +'%r %F')"
    }
else
    statusbar() {
        echo "$(bspc wm -g) | $(date +'%r %F')"
    }
fi

while true; do
    statusbar
    sleep 1s
done | dzen2 -fn monospace-11 &
