font_family         Fira Code
font_size           10

disable_ligatures   cursor

enable_audio_bell   no

map ctrl+shift+w    no_op
map ctrl+alt+w      close_window_with_confirmation ignore-shell
map ctrl+shift+q    no_op
map ctrl+alt+q      close_tab
